name: Deploy to Timeweb via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: vh314.timeweb.ru
          port: 22
          username: co89321
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./"
          remote_path: "/home/c/co89321/public_html/test/github_cc_autodeploy3"
          sftp_only: true
