name: Deploy via Git Pull Webhook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deployment webhook
      run: |
        echo "Deployment will be triggered via GitHub webhook"
        echo "Make sure webhook is configured at: https://github.com/dk-test-organization/php-demo-app3/settings/hooks"
